/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import services.UtilisateurService;

/**
 *
 * @author cli
 */
public class LoginForm extends javax.swing.JFrame {
    private UtilisateurService utilisateurService;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setTitle("Authentification");
        utilisateurService = new UtilisateurService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logintxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JPasswordField();
        seconnecterbtn = new javax.swing.JButton();
        quitterbtn = new javax.swing.JButton();
        passwordoubliebtn = new javax.swing.JButton();
        inscrirebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Page :"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login :");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mot De Passe :");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        logintxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        logintxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        passwordtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });

        seconnecterbtn.setText("Se Connecter");
        seconnecterbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        seconnecterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seconnecterbtnActionPerformed(evt);
            }
        });

        quitterbtn.setText("Quitter");
        quitterbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quitterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterbtnActionPerformed(evt);
            }
        });

        passwordoubliebtn.setBackground(new java.awt.Color(204, 255, 204));
        passwordoubliebtn.setForeground(new java.awt.Color(0, 51, 255));
        passwordoubliebtn.setText("Mot De Passe Oublié ?");
        passwordoubliebtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        passwordoubliebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordoubliebtnActionPerformed(evt);
            }
        });

        inscrirebtn.setForeground(new java.awt.Color(0, 0, 204));
        inscrirebtn.setText("S'inscrire !");
        inscrirebtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inscrirebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrirebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(seconnecterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quitterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordoubliebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(inscrirebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscrirebtn))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordoubliebtn))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seconnecterbtn)
                    .addComponent(quitterbtn))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void seconnecterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seconnecterbtnActionPerformed
        // TODO add your handling code here:
         String login = logintxt.getText().trim();
    String password = new String(passwordtxt.getPassword());

    if (login.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Veuillez saisir le login et le mot de passe.",
                "Erreur",
                JOptionPane.ERROR_MESSAGE
        );
        return; 
    }

    boolean ok = utilisateurService.checkLogin(login, password);

    if (ok) {
        JOptionPane.showMessageDialog(
                this,
                "Connexion réussie, bienvenue " + login + " !",
                "Succès",
                JOptionPane.INFORMATION_MESSAGE
        );

        Main m = new Main();   
        m.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(
                this,
                "Login ou mot de passe incorrect.",
                "Erreur",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_seconnecterbtnActionPerformed

    private void quitterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterbtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitterbtnActionPerformed

    private void passwordoubliebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordoubliebtnActionPerformed
        // TODO add your handling code here:
         String email = JOptionPane.showInputDialog(
            this,
            "Veuillez saisir votre adresse e-mail :",
            "Mot de passe oublié",
            JOptionPane.QUESTION_MESSAGE
    );

    if (email == null) {
        // L'utilisateur a cliqué sur Annuler
        return;
    }

    email = email.trim();
    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Veuillez saisir une adresse e-mail.",
                "Erreur",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    try {
        boolean ok = utilisateurService.resetPassword(email);

        if (ok) {
            JOptionPane.showMessageDialog(
                    this,
                    "Un nouveau mot de passe temporaire a été envoyé à : " + email,
                    "Succès",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Aucun utilisateur n'est enregistré avec cet e-mail.",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(
                this,
                "Une erreur s'est produite lors de l'envoi de l'e-mail.\n" + ex.getMessage(),
                "Erreur",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_passwordoubliebtnActionPerformed

    private void inscrirebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrirebtnActionPerformed
        // TODO add your handling code here:
        JTextField loginField = new JTextField();
        JTextField emailField = new JTextField();
        JPasswordField passwordField = new JPasswordField();
        JPasswordField confirmField = new JPasswordField();

    Object[] message = {
        "Login :", loginField,
        "Email :", emailField,
        "Mot de passe :", passwordField,
        "Confirmer le mot de passe :", confirmField
    };

    int option = JOptionPane.showConfirmDialog(
            this,
            message,
            "Créer un nouveau compte",
            JOptionPane.OK_CANCEL_OPTION
    );

    if (option != JOptionPane.OK_OPTION) {
        return; 
    }

    String login = loginField.getText().trim();
    String email = emailField.getText().trim();
    String password = new String(passwordField.getPassword());
    String confirm = new String(confirmField.getPassword());

    // Validations simples
    if (login.isEmpty() || email.isEmpty() || password.isEmpty() || confirm.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Veuillez remplir tous les champs.",
                "Erreur",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    if (!password.equals(confirm)) {
        JOptionPane.showMessageDialog(
                this,
                "Les mots de passe ne correspondent pas.",
                "Erreur",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // Appel au service
    boolean ok = utilisateurService.register(login, email, password);

    if (!ok) {
        JOptionPane.showMessageDialog(
                this,
                "Login ou e-mail déjà utilisé.",
                "Erreur",
                JOptionPane.ERROR_MESSAGE
        );
    } else {
        JOptionPane.showMessageDialog(
                this,
                "Compte créé avec succès !\nVous pouvez maintenant vous connecter.",
                "Succès",
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    }//GEN-LAST:event_inscrirebtnActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inscrirebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField logintxt;
    private javax.swing.JButton passwordoubliebtn;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JButton quitterbtn;
    private javax.swing.JButton seconnecterbtn;
    // End of variables declaration//GEN-END:variables
}
