/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import services.VenteAgroService;

/**
 *
 * @author cli
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setTitle("Gestion d'Une Coopérative Agricole");
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        GestionMenu = new javax.swing.JMenu();
        AgriculteurMenuItem = new javax.swing.JMenuItem();
        ProduitsMenuItem = new javax.swing.JMenuItem();
        VentesMenuItem = new javax.swing.JMenuItem();
        FiltrageMenu = new javax.swing.JMenu();
        ParCommuneMenu = new javax.swing.JMenuItem();
        ParTypeMenu = new javax.swing.JMenuItem();
        StatistiquesMenu = new javax.swing.JMenu();
        QuantiteMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        desktopPane.setForeground(new java.awt.Color(240, 240, 240));

        GestionMenu.setMnemonic('f');
        GestionMenu.setText("Gestion");

        AgriculteurMenuItem.setMnemonic('o');
        AgriculteurMenuItem.setText("Agriculteurs");
        AgriculteurMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgriculteurMenuItemActionPerformed(evt);
            }
        });
        GestionMenu.add(AgriculteurMenuItem);

        ProduitsMenuItem.setMnemonic('s');
        ProduitsMenuItem.setText("Produits");
        ProduitsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProduitsMenuItemActionPerformed(evt);
            }
        });
        GestionMenu.add(ProduitsMenuItem);

        VentesMenuItem.setMnemonic('a');
        VentesMenuItem.setText("Ventes");
        VentesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentesMenuItemActionPerformed(evt);
            }
        });
        GestionMenu.add(VentesMenuItem);

        menuBar.add(GestionMenu);

        FiltrageMenu.setMnemonic('e');
        FiltrageMenu.setText("Filtrage");

        ParCommuneMenu.setMnemonic('t');
        ParCommuneMenu.setText("Par Commune");
        ParCommuneMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParCommuneMenuActionPerformed(evt);
            }
        });
        FiltrageMenu.add(ParCommuneMenu);

        ParTypeMenu.setMnemonic('y');
        ParTypeMenu.setText("Par Type");
        ParTypeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParTypeMenuActionPerformed(evt);
            }
        });
        FiltrageMenu.add(ParTypeMenu);

        menuBar.add(FiltrageMenu);

        StatistiquesMenu.setMnemonic('h');
        StatistiquesMenu.setText("Graphique");

        QuantiteMenuItem.setMnemonic('c');
        QuantiteMenuItem.setText("Quantités Vendus / Produit");
        QuantiteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantiteMenuItemActionPerformed(evt);
            }
        });
        StatistiquesMenu.add(QuantiteMenuItem);

        menuBar.add(StatistiquesMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgriculteurMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgriculteurMenuItemActionPerformed
        // TODO add your handling code here:
        
        AgriculteurForm af = new AgriculteurForm();
        desktopPane.add(af);
        af.setVisible(true);
    }//GEN-LAST:event_AgriculteurMenuItemActionPerformed

    private void ParTypeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParTypeMenuActionPerformed
        // TODO add your handling code here:
    TypeForm tf = new TypeForm();
    desktopPane.add(tf);        
    tf.setVisible(true);
    }//GEN-LAST:event_ParTypeMenuActionPerformed

    private void QuantiteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantiteMenuItemActionPerformed
        // TODO add your handling code here:
        QuantiteGraphe qg = new QuantiteGraphe();
        VenteAgroService vs = new VenteAgroService();
        qg.loadGraphQuantitesParProduit(vs.findAll());
        desktopPane.add(qg);
        qg.pack(); 
        int x = (desktopPane.getWidth() - qg.getWidth()) / 2;
        int y = (desktopPane.getHeight() - qg.getHeight()) / 2;
        qg.setLocation(x, y);
        qg.setVisible(true);
    }//GEN-LAST:event_QuantiteMenuItemActionPerformed

    private void ParCommuneMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParCommuneMenuActionPerformed
        // TODO add your handling code here:
    CommuneForm svf = new CommuneForm();
    desktopPane.add(svf);        
    svf.setVisible(true);
    }//GEN-LAST:event_ParCommuneMenuActionPerformed

    private void ProduitsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProduitsMenuItemActionPerformed
        // TODO add your handling code here:
        
        ProduitForm pf = new ProduitForm();
        desktopPane.add(pf);
        pf.setVisible(true);
    }//GEN-LAST:event_ProduitsMenuItemActionPerformed

    private void VentesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentesMenuItemActionPerformed
        // TODO add your handling code here:
        VenteForm vf = new VenteForm();
        desktopPane.add(vf);
        vf.setVisible(true);
    }//GEN-LAST:event_VentesMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgriculteurMenuItem;
    private javax.swing.JMenu FiltrageMenu;
    private javax.swing.JMenu GestionMenu;
    private javax.swing.JMenuItem ParCommuneMenu;
    private javax.swing.JMenuItem ParTypeMenu;
    private javax.swing.JMenuItem ProduitsMenuItem;
    private javax.swing.JMenuItem QuantiteMenuItem;
    private javax.swing.JMenu StatistiquesMenu;
    private javax.swing.JMenuItem VentesMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
