/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.ProduitAgro;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.ProduitAgroService;


/**
 *
 * @author cli
 */
public class ProduitForm extends javax.swing.JInternalFrame {
    
    ProduitAgroService ps = null;
    DefaultTableModel model = null;
    static int id;
    
    public ProduitForm() {
        initComponents();
        ps = new ProduitAgroService();
        model = (DefaultTableModel) listeproduits.getModel();
        load();
    }
    
    public void load() {
        model.setRowCount(0);
        for (ProduitAgro p : ps.findAll()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getNom(),
                p.getType(),
                p.getPrixKg()
            });
        }
    }
    
    private void vider() {
        id = 0;
        nomtxt.setText("");
        typetxt.setText("");
        prixtxt.setText("");
    }
    
  

    /**
     * Creates new form ProduitForm
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomtxt = new javax.swing.JTextField();
        typetxt = new javax.swing.JTextField();
        prixtxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ajouterbtn = new javax.swing.JButton();
        supprimerbtn = new javax.swing.JButton();
        modifierbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeproduits = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Liste Produits"));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des Produits");

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations Produit"));

        jLabel1.setText("Nom :");

        jLabel2.setText("Type :");

        jLabel3.setText("Prix / Kg :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(typetxt)
                    .addComponent(prixtxt))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prixtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        ajouterbtn.setText("Ajouter");
        ajouterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterbtnActionPerformed(evt);
            }
        });

        supprimerbtn.setText("Supprimer");
        supprimerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerbtnActionPerformed(evt);
            }
        });

        modifierbtn.setText("Modifier");
        modifierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modifierbtn)
                    .addComponent(supprimerbtn)
                    .addComponent(ajouterbtn))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(ajouterbtn)
                .addGap(44, 44, 44)
                .addComponent(supprimerbtn)
                .addGap(65, 65, 65)
                .addComponent(modifierbtn)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste Produits :"));

        listeproduits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Type", "Prix / Kg"
            }
        ));
        listeproduits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeproduitsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeproduits);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterbtnActionPerformed
        // TODO add your handling code here:
        
       double prix = Double.parseDouble(prixtxt.getText());
        ps.create(new ProduitAgro( nomtxt.getText(), typetxt.getText(), prix));
        vider();
        load();
    }//GEN-LAST:event_ajouterbtnActionPerformed

    private void supprimerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerbtnActionPerformed
              
        int reponse = JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment supprimer ce Produit ?");
        
        if(reponse == 0){
            ps.delete(ps.findById(id));
            
            load();
            vider();
        }
    }//GEN-LAST:event_supprimerbtnActionPerformed

    private void listeproduitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeproduitsMouseClicked
        // TODO add your handling code here:
        id = Integer.parseInt(model.getValueAt(listeproduits.getSelectedRow(), 0).toString());
        nomtxt.setText(model.getValueAt(listeproduits.getSelectedRow(), 1).toString());
        typetxt.setText(model.getValueAt(listeproduits.getSelectedRow(), 2).toString());
        prixtxt.setText(model.getValueAt(listeproduits.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_listeproduitsMouseClicked

    private void modifierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierbtnActionPerformed
        // TODO add your handling code here:
         int reponse = JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment modifier cet Agriculteur ?");
        
        if(reponse == 0){
            double prix = Double.parseDouble(prixtxt.getText());
            ps.update(new ProduitAgro(id, nomtxt.getText(), typetxt.getText(), prix));
            load();
            vider();
        }
    }//GEN-LAST:event_modifierbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeproduits;
    private javax.swing.JButton modifierbtn;
    private javax.swing.JTextField nomtxt;
    private javax.swing.JTextField prixtxt;
    private javax.swing.JButton supprimerbtn;
    private javax.swing.JTextField typetxt;
    // End of variables declaration//GEN-END:variables
}
