/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.VenteAgro;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;


/**
 *
 * @author cli
 */
public class QuantiteGraphe extends javax.swing.JInternalFrame {
    
     private javax.swing.JPanel graphePanel;

    /**
     * Creates new form QuantiteGraphe
     */
    public QuantiteGraphe() {
        initComponents();
        
    }
    
   
    public void loadGraphQuantitesParProduit(List<VenteAgro> ventes) {

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        Map<String, Double> mapQuantites = new HashMap<>();

        
        System.out.println("Nombre de ventes reçues pour le graphe : " + ventes.size());

        for (VenteAgro v : ventes) {
            if (v.getProduit() == null || v.getProduit().getNom() == null) continue;

            String produit = v.getProduit().getNom();
            double qte = v.getQuantite();

            mapQuantites.merge(produit, qte, Double::sum);
        }

        // DEBUG : voir les quantités par produit
        for (Map.Entry<String, Double> e : mapQuantites.entrySet()) {
            System.out.println("Produit = " + e.getKey() + " | Quantité = " + e.getValue());
            dataset.addValue(e.getValue(), "Quantité vendue", e.getKey());
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Quantités vendues par produit",
                "Produit",
                "Quantité vendue",
                dataset,
                PlotOrientation.VERTICAL,
                false,
                true,
                false
        );

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setMouseWheelEnabled(true);
        
         chartPanel.setPreferredSize(new java.awt.Dimension(800, 400));
         
         
        panelGraph.removeAll();
        panelGraph.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panelGraph.add(chartPanel, gbc);
        panelGraph.revalidate();
        panelGraph.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGraph = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelGraph.setBackground(new java.awt.Color(255, 204, 255));
        panelGraph.setBorder(javax.swing.BorderFactory.createTitledBorder("Graphe Des Ventes :"));

        javax.swing.GroupLayout panelGraphLayout = new javax.swing.GroupLayout(panelGraph);
        panelGraph.setLayout(panelGraphLayout);
        panelGraphLayout.setHorizontalGroup(
            panelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        panelGraphLayout.setVerticalGroup(
            panelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelGraph;
    // End of variables declaration//GEN-END:variables
}
