/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.time.LocalDate;
import java.time.ZoneId;
import entities.Agriculteur;
import entities.ProduitAgro;
import entities.VenteAgro;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.AgriculteurService;
import services.ProduitAgroService;
import services.VenteAgroService;

/**
 *
 * @author cli
 */
public class VenteForm extends javax.swing.JInternalFrame {

    private VenteAgroService vs;
    private ProduitAgroService ps;
    private AgriculteurService as;
    private DefaultTableModel model;
    private static int id;

    /**
     * Creates new form VenteForm
     */
    public VenteForm() {
        initComponents();
        vs = new VenteAgroService();
        ps = new ProduitAgroService();
        as = new AgriculteurService();
        model = (DefaultTableModel) listeventes.getModel();
        loadCombos();
        load();
    }

    private void loadCombos() {
        produitcombo.removeAllItems();
        for (ProduitAgro p : ps.findAll()) {
            produitcombo.addItem(p);
        }

        agriculteurcombo.removeAllItems();
        for (Agriculteur a : as.findAll()) {
            agriculteurcombo.addItem(a);
        }

        // date par défaut : aujourd'hui
        jCalendarComboBox1.setDate(new Date());

    }

    public void load() {
        model.setRowCount(0);
        for (VenteAgro v : vs.findAll()) {
            double prixKg = v.getProduit().getPrixKg();
            double qte = v.getQuantite();
            double revenu = prixKg * qte;

            model.addRow(new Object[]{
                v.getId(),
                v.getProduit().getNom(),
                v.getProduit().getId(),
                v.getAgriculteur().getNom(),
                v.getAgriculteur().getId(),
                v.getDateVente(),
                qte,
                revenu
            });
        }
    }

    private void vider() {
        id = 0;
        produitcombo.setSelectedIndex(-1);
        agriculteurcombo.setSelectedIndex(-1);
        quantitetxt.setText("");
        jCalendarComboBox1.setDate(new Date());
        listeventes.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        produitcombo = new javax.swing.JComboBox();
        agriculteurcombo = new javax.swing.JComboBox();
        quantitetxt = new javax.swing.JTextField();
        jCalendarComboBox1 = new de.wannawork.jcalendar.JCalendarComboBox();
        jPanel2 = new javax.swing.JPanel();
        ajouterbtn = new javax.swing.JButton();
        modifierbtn = new javax.swing.JButton();
        supprimerbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeventes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des Ventes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations Vente"));

        jLabel1.setText("Produit :");

        jLabel2.setText("Agriculteur :");

        jLabel3.setText("Quantité :");

        jLabel4.setText("Date :");

        produitcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        agriculteurcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        agriculteurcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agriculteurcomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(produitcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agriculteurcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quantitetxt)
                    .addComponent(jCalendarComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(produitcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(agriculteurcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantitetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jCalendarComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        ajouterbtn.setBackground(new java.awt.Color(255, 255, 204));
        ajouterbtn.setText("Ajouter");
        ajouterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterbtnActionPerformed(evt);
            }
        });

        modifierbtn.setBackground(new java.awt.Color(255, 255, 204));
        modifierbtn.setText("Modifier");
        modifierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierbtnActionPerformed(evt);
            }
        });

        supprimerbtn.setBackground(new java.awt.Color(255, 255, 204));
        supprimerbtn.setText("Supprimer");
        supprimerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supprimerbtn)
                    .addComponent(modifierbtn)
                    .addComponent(ajouterbtn))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(ajouterbtn)
                .addGap(35, 35, 35)
                .addComponent(modifierbtn)
                .addGap(55, 55, 55)
                .addComponent(supprimerbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste Ventes :"));

        listeventes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Vente", "Produit", "ID Produit", "Agriculteur", "ID Agriculteur", "Date", "Quantité (Kg)", "Revenus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listeventes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeventesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeventes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agriculteurcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agriculteurcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agriculteurcomboActionPerformed

    private void ajouterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterbtnActionPerformed
        // TODO add your handling code here:
        ProduitAgro p = (ProduitAgro) produitcombo.getSelectedItem();
        Agriculteur a = (Agriculteur) agriculteurcombo.getSelectedItem();
        String qteStr = quantitetxt.getText().trim();
        Date d = jCalendarComboBox1.getDate();

        if (p == null || a == null) {
            JOptionPane.showMessageDialog(this,
                    "Veuillez choisir un produit et un agriculteur.",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (d == null) {
            JOptionPane.showMessageDialog(this,
                    "Veuillez choisir une date de vente.",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (qteStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Veuillez saisir la quantité.",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        double qte;
        try {
            qte = Double.parseDouble(qteStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Quantité invalide.",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (vs.existsByAgriculteurAndProduit(a.getId(), p.getId())) {
            JOptionPane.showMessageDialog(this,
                    "Une vente existe déjà pour cet agriculteur et ce produit.",
                    "Doublon",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        LocalDate dateVente = d.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        VenteAgro v = new VenteAgro(dateVente, qte, p, a);

        if (vs.create(v)) {
            JOptionPane.showMessageDialog(this,
                    "Vente ajoutée avec succès.",
                    "Succès",
                    JOptionPane.INFORMATION_MESSAGE);
            load();
            vider();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Erreur lors de l'ajout de la vente.",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ajouterbtnActionPerformed

    private void modifierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierbtnActionPerformed
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier cette Vente  ?");

        if (reponse == 0) {
            ProduitAgro p = (ProduitAgro) produitcombo.getSelectedItem();
            Agriculteur a = (Agriculteur) agriculteurcombo.getSelectedItem();
            double qte = Double.parseDouble(quantitetxt.getText());

            java.util.Date d = jCalendarComboBox1.getDate();
            LocalDate date = d.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

            vs.update(new VenteAgro(id, date, qte, p, a));

            load();
            vider();
        }
    }//GEN-LAST:event_modifierbtnActionPerformed

    private void supprimerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerbtnActionPerformed
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer cette Vente ?");

        if (reponse == 0) {
            vs.delete(vs.findById(id));

            load();
            vider();
        }
    }//GEN-LAST:event_supprimerbtnActionPerformed

    private void listeventesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeventesMouseClicked
        // TODO add your handling code here:
        int row = listeventes.getSelectedRow();

        id = Integer.parseInt(model.getValueAt(row, 0).toString());

        String nomProduit = model.getValueAt(row, 1).toString();

        for (int i = 0; i < produitcombo.getItemCount(); i++) {
            ProduitAgro p = (ProduitAgro) produitcombo.getItemAt(i);
            if (p.getNom().equals(nomProduit)) {
                produitcombo.setSelectedIndex(i);
                break;
            }
        }

        String nomAgriculteur = model.getValueAt(row, 3).toString();

        for (int i = 0; i < agriculteurcombo.getItemCount(); i++) {
            Agriculteur a = (Agriculteur) agriculteurcombo.getItemAt(i);
            if (a.getNom().equals(nomAgriculteur)) {
                agriculteurcombo.setSelectedIndex(i);
                break;
            }
        }

        quantitetxt.setText(model.getValueAt(row, 6).toString());

        String dateStr = model.getValueAt(row, 5).toString();
        LocalDate ld = LocalDate.parse(dateStr);

        Date d = Date.from(ld.atStartOfDay(ZoneId.systemDefault()).toInstant());
        jCalendarComboBox1.setDate(d);
    }//GEN-LAST:event_listeventesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox agriculteurcombo;
    private javax.swing.JButton ajouterbtn;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeventes;
    private javax.swing.JButton modifierbtn;
    private javax.swing.JComboBox produitcombo;
    private javax.swing.JTextField quantitetxt;
    private javax.swing.JButton supprimerbtn;
    // End of variables declaration//GEN-END:variables
}
